log_format detailed_log '$remote_addr - $remote_user - [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        '$request_time $upstream_response_time '
                        '"$http_x_forwarded_for" '; 

server {
    listen 80;
    server_name prometheus.bloggyspace.local;

    client_max_body_size 20M;

    error_log /var/log/nginx/error.log error;

    proxy_set_header  Host               $host;
    proxy_set_header  X-Real-IP          $remote_addr;
    proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto  $scheme;


      location / {
        proxy_pass http://prometheus:9090;
        proxy_redirect off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        access_log /var/log/prometheus_access.log detailed_log;
        error_log /var/log/prometheus_error.log error;
    }

}

server {
    listen 80;
    server_name grafana.bloggyspace.local;

    client_max_body_size 20M;

        location / {
            proxy_pass http://grafana:3000;
            proxy_redirect off;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 3600s;

            access_log /var/log/grafana_access.log detailed_log;
            error_log /var/log/grafana_error.log error;
        }
}

server {
    listen 80;
    server_name portainer.bloggyspace.local;

    client_max_body_size 20M;

    error_log /var/log/nginx/error.log error;

    proxy_set_header  Host               $host;
    proxy_set_header  X-Real-IP          $remote_addr;
    proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto  $scheme;


      location / {
        proxy_pass http://portainer:9000;
        proxy_redirect off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Connection "";

        access_log /var/log/portainer_access.log detailed_log;
        error_log /var/log/portainer_error.log error;
    }

}

server {
    listen 80;
    server_name alertmanager.bloggyspace.local;

    location / {
        proxy_pass http://alertmanager:9093;
        proxy_redirect off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}